### ISSUE TITLE
TypeScript export and import/named rule

### ISSUE THREAD

**Issue by kirill-konshin** [benmosher/eslint-plugin-import#1282]
TypeScript's exported types/interfaces does not work with `import/named` rule.

File 'xxx.ts':

```ts
export type ScpRouteProps = ReactRouter.RouteProps & {
    access?: boolean;
    title: string;
};
```

Then import it in different file:
```ts
import {ScpRouteProps} from './xxx';
```

Will result in error:

```
7:5  error  ScpRouteProps not found in './xxx'    import/named
```

Same error when importing:

```ts
import {WrappedFieldProps} from 'redux-form';
// 1:9  error  WrappedFieldProps not found in 'redux-form'                import/named
```

Or

```ts
import {AutoSizer, Column, ColumnProps, Table, TableProps} from 'react-virtualized';
// /xxx/web/src/components/VirtualizedTable.tsx
//  3:28  error  ColumnProps not found in 'react-virtualized'  import/named
//  3:48  error  TableProps not found in 'react-virtualized'   import/named
```

**Comment by ljharb** [comment]
It seems like the right thing to do here is to include TypeScript `export type` exports in the ExportMap, which should make everything Just Work.

**Comment by kirill-konshin** [comment]
Not just `type`, `interface`s too. Any ideas how to do that? I'm totally not familiar with plugin's codebase...

**Comment by ljharb** [comment]
Presumably somewhere in https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js#L335 - cc @benmosher

**Comment by lednhatkhanh** [comment]
Getting the same error

**Comment by JustFly1984** [comment]
I'm getting the same error in my Gatsby.js TS project.

**Comment by jpickwell** [comment]
May also want to check a package's `package.json` for a `types` key which points to a TypeScript type definition file (`*.d.ts`).

**Comment by Primajin** [comment]
Weirdly `export type foo` isn't recognized for me anymore, while `export interface bar` is.

**Comment by bradennapier** [comment]
Was the ExportMap a comment about how to fix this bug via PR or is there some config to fix this?  Just hit this one as well :-\ pretty major rule to disable.

**Comment by bradennapier** [comment]
@ljharb got this fixed in pr #1304 - any way to get this merged ASAP?  It kills our libraries pretty badly and we are a large part through moving to eslint from tslint. :-)

**Comment by ljharb** [comment]
@bradennapier even if it were; there's only one person who can cut a release, so it's not likely to be published asap.

**Comment by bradennapier** [comment]
Ahh, ok thanks.

**Comment by schmod** [comment]
FYI, this only appears to happen when using `@typescript-eslint/parser`, but works correctly with (the now-deprecated) `typescript-eslint-parser`.

**Comment by JSteunou** [comment]
like @schmod said the bug is present with when using `@typescript-eslint/parser` and unfortunately still present, I dont understand why, @bradennapier fix seemed ok :suspect:

**Comment by JSteunou** [comment]
it seems to only happen when the type are in a separate `index.d.ts` file

**Comment by dontsave** [comment]
I'm getting this issue with `@typescript-eslint/parser` as well. Perfectly fine named exports are erroring while being imported

**Comment by laustdeleuran** [comment]
I'm experiencing this error as well, with the package `react-intl` v2.9.0. 
`import { InjectedIntlProps } from 'react-intl';` currently errors

**Comment by PejmanNik** [comment]
So in the alexgorbatchev/eslint-import-resolver-typescript#31 it passed to `eslint-plugin-import` and here pass it back? how I can help to resolve this issue?
Thank you

**Comment by apedroferreira** [comment]
I'm still getting this, for example when importing the Keyframe interface from 'styled-components':

```import { Keyframes as KeyframesType } from 'styled-components'````

**Comment by dawndong1988** [comment]
> it seems to only happen when the type are in a separate `index.d.ts` file

The same. Is there any solution? We have to disable the rule for now.

**Comment by Maxim-Mazurok** [comment]
Adding this to `.eslintrc.js`:
```js
settings: {
  "import/resolver": {
    typescript: {
      alwaysTryTypes: true
    }
  }
}
```
seems to solve **this** problem.
Unfortunetly, it introduces another issue: `No default export found in imported module "react"      import/default` when doing `import React from "react"` or `import * as React from "react"`.

**Comment by ljharb** [comment]
That’s because typescript’s module system is broken unless you enable synthetic imports and es module interop. If you enable those, what happens?

**Comment by Ffdominikkoller** [comment]
Just to give a feedback, i had same issue and had all tried that should fix this issue. Nothing helped. So i played more with the settings and fixed it with setting the babel/env preset modules to "commonjs". Was set to "false".
So babelrc:

```json
"presets": [
        [
            "@babel/env",
            {
                "useBuiltIns": "entry",
                "corejs": 3,
                "modules": "commonjs"
            }
        ],
        "@babel/react",
        "@babel/typescript"
    ]
```

**Comment by g3tr1ght** [comment]
> Just to give a feedback, i had same issue and had all tried that should fix this issue. Nothing helped. So i played more with the settings and fixed it with setting the babel/env preset modules to "commonjs". Was set to "false".
> So babelrc:
> 
> ```json
> "presets": [
>         [
>             "@babel/env",
>             {
>                 "useBuiltIns": "entry",
>                 "corejs": 3,
>                 "modules": "commonjs"
>             }
>         ],
>         "@babel/react",
>         "@babel/typescript"
>     ]
> ```

I'm afraid you're missing the point of modules entry in babel/env preset and most likely you aren't running eslint cli, but rather use it as a webpack (or other bundler) plugin/loader.
Here's why this particular combination works for you: https://github.com/import-js/eslint-plugin-import/blob/94d6739ebc9fc0e0f06319c90ffad32da94e8a41/src/rules/named.js#L79
And if you use "modules": "commonjs" (especially in production), as a result you have larger bundle size, since webpack can't tree-shake commonjs.

**Comment by Shunya078** [comment]
> Issue seems to appear when importing interface from @types folder. If package has index.d.ts in it's own folder - it works fine.

I found a similar problem and am now using the following to ignore the lint rules. (Because there is no problem in the behavior on the web)
`// eslint-disable-next-line import/named`

Currently, interfaces are defined in a set of files called "interfaces".
Is it possible to allow typedefs for folders in the "interfaces" county in general?

I apologize if this is a lack of knowledge on my part. Please respond.

**Comment by bogem** [comment]
Possible solution that works for us:
> import **type** { Keyframes } from 'styled-components'

But it's only available for TS3.8+
