### ISSUE TITLE
Bug: import/no-deprecated doesn't work with typescript

### ISSUE THREAD

**Issue by Hotell** [benmosher/eslint-plugin-import#1315]
**.eslintrc.js**

```js
module.exports = {
  root: true,
  plugins: [
    '@typescript-eslint',
    'react',
    'react-hooks',
    'jsx-a11y',
    'filenames',
    'import',
  ],
  rules: {
    'import/no-deprecated': 'error',
  },
};
```

**Code:**

```ts
// usage.ts

import { foo } from './foo';

console.log(foo());

// foo.ts
/**
 * this is what you get when you trust a mouse talk show
 * @deprecated don't use this!
 * @returns {string} nonsense
 */
export function foo() {
  return 'bar';
}
```

**lint run:**

```sh
eslint --ignore-path .gitignore --ext .ts,.tsx packages
```

will produce NO lint errors

**Comment by benmosher** [comment]
I think you need to configure a parser. I just added some tests and it seems to be working, _if_ a TypeScript parser is configured. Might also need the TS resolver:

```settings: {
        'import/parsers': { '@typescript-eslint/parser': ['.ts'] },
        'import/resolver': { 'eslint-import-resolver-typescript': true },
      },```

**Comment by Hotell** [comment]
Fixed by https://github.com/benmosher/eslint-plugin-import/pull/1257

thx!

**Comment by digeomel** [comment]
Is the fix released already? I can't tell from the comments on #1257

**Comment by ljharb** [comment]
Long fixed. Try it and see.

**Comment by digeomel** [comment]
It still doesn't work for me. I was using RxJs forkJoin and it was not marked as deprecated in vscode (other eslint warnings work fine). A colleague using IntelliJ (which I guess uses an internal check, not eslint-based) pointed it out to me.

**Comment by ljharb** [comment]
Please file a new issue for that.

**Comment by justingolden21** [comment]
Adding `'import/no-deprecated': 'error',` crashes `pnpm lint` for me, and it works otherwise. I have `"eslint-plugin-import": "2.31.0",` in `package.json`

**Comment by ljharb** [comment]
@justingolden21 if it works with just `eslint` on the command line, and not with pnpm lint, it's a bug with pnpm; similarly, if it works with an npm-installed dep tree and not a pnpm-installed one, then it's also a bug with pnpm (but _possibly_ one we could still handle, and I'd need more information).

If it's still something we should look at, please file a new issue.
